# -*- coding: utf-8 -*-
"""recom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DC5KPOSs7TXtVzqUYtZlMQGgk_rY9QCm
"""

import pandas as pd
import re

def filter_hotels_by_budget(hotels_df, lower_budget, upper_budget, min_rating=8):
    # Extract numeric part of 'price' and 'score' columns and convert to float
    hotels_df['price'] = hotels_df['price'].apply(lambda x: float(re.sub(r'[^\d.]', '', x)))
    hotels_df['score'] = hotels_df['score'].str.extract(r'(\d+\.\d+)', expand=False).astype(float)
    filtered_hotels = hotels_df[(hotels_df['price'] >= lower_budget) &
                                (hotels_df['price'] <= upper_budget) &
                                (hotels_df['score'] > min_rating)]
    return filtered_hotels

def display_hotels(filtered_hotels):
    for index, row in filtered_hotels.iterrows():
        print()
        print(f"Name of the hotel: {row['hotel']}")
        print(f"Cost per night: ${row['price']:.3f}")
        print(f"Ratings: {row['score']} - {row['avg review']} ({row['reviews count']} reviews)")
        print()
        print()

def main():
    lower_budget = float(input("Enter the lower budget (per night) in USD: "))
    upper_budget = float(input("Enter the upper budget (per night) in USD: "))

    # Load hotel data from CSV
    hotels_df = pd.read_csv('London_hotels_data.csv')

    # Filter hotels based on budget and minimum rating
    filtered_hotels = filter_hotels_by_budget(hotels_df, lower_budget, upper_budget)

    if filtered_hotels.empty:
        print("No hotels found within the specified budget range with a rating above 8.")
    else:
        # Display filtered hotels
        print(f"\nHotels within the budget range of ${lower_budget:.2f} to ${upper_budget:.2f} per night with a rating above 8:")
        display_hotels(filtered_hotels)

if __name__ == '__main__':
    main()

